language: ruby

before_install:
  - gem install bundler

script:
 - bundle install
 - bundle exec rake test

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer #https://github.com/gjtorikian/html-proofer/issues/381
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

branches:
  only:
 - gh-pages

sudo: false # route your build to the container-based infrastructure for a faster build
